/*This file has been generated by Phaser Assets Loader (https://github.com/naveedurrehman/PhaserAssetsLoader)*/


function PhaserAssetsLoader_assets(obj)
{



/* Loading Images */
obj.load.image('imgcircle1', 'assets/images/circle1.png')
obj.load.image('imgcircle2', 'assets/images/more/circle2.png')

/* Loading Sprite Sheets */
obj.load.spritesheet('spteyes', 'assets/spritesheets/eyes@10x10x9.png',{ frameWidth: 10, frameHeight: 10, endFrame: 9 })

/* Loading Audio */
obj.load.audio('audhorn', ['assets/audio/horn.mp3'])

/* Loading Fonts */
obj.load.bitmapFont('fntninja', 'assets/fonts/ninja.png', 'assets/fonts/ninja.fnt')

/* Loading HTML */
obj.load.html('htmfrmName', 'assets/htmls/frmName.html')

}