<?
/*
       Phaser Assets Loader
       php -S localhost:8000
       http://localhost:8000/PhaserAssetsLoader.php?folder=assets
*/


/*Examples:

       Hardcoding the function call
       PhaserAssetsLoader(
              "assets",     //Assets folder to be scanned
              "test",       //Suffix for js function name [e.g. PhaserAssetsLoader_test] (optional)
              "PhaserAssetsLoader.js"     //Output to the file (optional)
       );
 */

 if(!isset($_GET["folder"])){echo "Asset folder must be provided (e.g. ?folder=assets)"; exit;}

PhaserAssetsLoader(
       $_GET["folder"],
       $_GET["folder"],
       $_GET["folder"].".js"
);

function PhaserAssetsLoader($assetsRootFolder,$functionName,$jsOutputFile)
{

       $jsOutput = "/*This file has been generated by Phaser Assets Loader (https://github.com/naveedurrehman/PhaserAssetsLoader)*/\r\n\r\n";
       $arrOutput = array();

       //Supported extensions
       $imageExtensions = array("png", "jpg", "jpeg");
       $audioExtensions = array("mp3");                 //Ogg file will be added if found.
       $fontExtensions = array("fnt");                  //fnt is xml file, the png should be in the same folder with same name
       $htmlExtensions = array("htm","html");        

       $keys = "";
       foreach(explode("\n",getAssets($assetsRootFolder)) as $file)
       {
              if(!file_exists($file)){continue;}
              $fileInfo = pathinfo($file);

              $key = $fileInfo['filename'];
              $key = explode("@",$key);
              $key = $key[0];

              
              if(strpos($keys,"[$key]")>0)
              {
                     $jsOutput .= "// Warning: The file name '$key' has been found in more than one folder (e.g. {$fileInfo['dirname']}).\r\n";
              }

              //Image assets
              if(in_array($fileInfo['extension'],$imageExtensions))
              {
                     if(strpos($fileInfo['filename'],"@")===false && !file_exists(str_replace($fileInfo['extension'],"fnt",$file)))
                     {
                            $key = "img$key";
                            $arrOutput['images'][] = "obj.load.image('$key', '$file')";
                            $keys.="[$key]";
                     }
                     else
                     {
                            $f = explode("@", $fileInfo['filename']);
                            if(count($f)>1)
                            {
                                   $key = "spt$key";
                                   $f=$f[1];
                                   $f = explode("x",$f);
                                   $w = $f[0];   $h = $f[1]; $fr = $f[2];
                            $arrOutput['spritesheets'][] = "obj.load.spritesheet('$key', '$file',{ frameWidth: $w, frameHeight: $h, endFrame: $fr })";
                                   $keys.="[$key]";
                            }
                     }
              }

              //Audio assets
              if(in_array($fileInfo['extension'],$audioExtensions))
              {
                     $ogg = str_replace(".mp3",".ogg",$file);
                     if(!file_exists($ogg)){$ogg="";}else{$ogg=",'$ogg'";}    
                     $key = "aud$key";       
                     $arrOutput['audio'][] = "obj.load.audio('$key', ['$file'$ogg])";
                     $keys.="[$key]";
              }

              //Bitmap Font assets
              if(in_array($fileInfo['extension'],$fontExtensions))
              {
                     $png = str_replace($fileInfo['extension'],"png",$file);
                     if(file_exists($png))
                     {
                            $key = "fnt$key";
                            $arrOutput['fonts'][] = "obj.load.bitmapFont('$key', '$png', '$file')";
                            $keys.="[$key]";
                     }
              }
              
              
              //HTML assets
              if(in_array($fileInfo['extension'],$htmlExtensions))
              {
                     $key = "htm$key";
                     $arrOutput['html'][] = "obj.load.html('$key', '$file')";
                     $keys.="[$key]";
              }
              
       }
       
       if($functionName){$functionName="_".$functionName;}
       $jsOutput .= "\r\nfunction PhaserAssetsLoader$functionName(obj)\r\n{\r\n\r\n";

       if(isset($arrOutput['images'])){
              $jsOutput .= "\r\n\r\n/* Loading Images */\r\n";
              $jsOutput .= implode("\r\n",$arrOutput['images']);
       }

       if(isset($arrOutput['spritesheets'])){
              $jsOutput .= "\r\n\r\n/* Loading Sprite Sheets */\r\n";
              $jsOutput .= implode("\r\n",$arrOutput['spritesheets']);
       }

       if(isset($arrOutput['audio'])){
              $jsOutput .= "\r\n\r\n/* Loading Audio */\r\n";
              $jsOutput .= implode("\r\n",$arrOutput['audio']);
       }

       if(isset($arrOutput['fonts'])){
              $jsOutput .= "\r\n\r\n/* Loading Fonts */\r\n";
              $jsOutput .= implode("\r\n",$arrOutput['fonts']);
       }

       if(isset($arrOutput['html'])){
       $jsOutput .= "\r\n\r\n/* Loading HTML */\r\n";
       $jsOutput .= implode("\r\n",$arrOutput['html']);
       }

       $jsOutput .= "\r\n\r\n}";

       echo $jsOutput;
       
       if($jsOutputFile)
       {
              file_put_contents($jsOutputFile,$jsOutput);
       }

}

function getAssets($folder)
{
       $r = '';

       foreach(scandir($folder) as $itemName)
       {
              if($itemName != "." && $itemName != "..")
              {
                     if(is_dir($folder."/".$itemName))
                     {
                            //$r[] = getAssets($folder."/".$itemName);
                            $r .= getAssets($folder."/".$itemName);
                     }
                     else
                     {
                            //$r[] = $folder."/".$itemName;
                            $r .= $folder."/".$itemName."\n";
                     }
              }
       }
       return($r);
}
?>